#!/usr/bin/env python3
"""Merge listing_details.csv with descriptions from refined.txt."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Iterable


def load_descriptions(path: Path) -> dict[str, str]:
    descriptions: dict[str, str] = {}
    lines = path.read_text(encoding="utf-8").splitlines()
    block: list[str] = []

    def flush() -> None:
        if not block:
            return
        header = block[0].strip()
        if "-" not in header:
            block.clear()
            return
        listing_id = header.split("-", 1)[0].strip()
        body = "\n".join(block[1:]).strip()
        descriptions[listing_id] = body
        block.clear()

    for line in lines:
        if line.strip():
            block.append(line)
        else:
            flush()
    flush()

    return descriptions


def merge_csv(
    details_path: Path, descriptions: dict[str, str], output_path: Path
) -> None:
    with details_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        fieldnames = reader.fieldnames or []
        if "description" not in fieldnames:
            fieldnames.append("description")
        rows = list(reader)

    for row in rows:
        listing_id = (row.get("listing_id") or "").strip()
        row["description"] = descriptions.get(listing_id, "")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Attach descriptions from refined.txt to listing_details.csv"
    )
    parser.add_argument(
        "--details-csv",
        type=Path,
        default=Path("listing_details.csv"),
        help="CSV generated by export_listing_details.py",
    )
    parser.add_argument(
        "--refined",
        type=Path,
        default=Path("refined.txt"),
        help="Refined descriptions file (refine_listings.py output).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("listing_details_with_descriptions.csv"),
        help="Path for the merged CSV output.",
    )
    args = parser.parse_args(argv)

    descriptions = load_descriptions(args.refined)
    merge_csv(args.details_csv, descriptions, args.output)
    print(
        f"Merged {len(descriptions)} descriptions into {args.details_csv} -> {args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
